### ISSUE TITLE
Error: object FirefoxLauncher can't be used in 'await' expression

### ISSUE THREAD

**Issue by therealpurplemana** [michaeleveringham/mokr#1]
Hi, thanks for the project.  When I try to run a scrape for the first time, I get the error:  Failed to scrape! Error: object FirefoxLauncher can't be used in 'await' expression

This is the command I used: mokr scrape --type "firefox" https://www.google.com

The browsers appear to have installed correctly

Am I doing something wrong?

**Comment by michaeleveringham** [comment]
@therealpurplemana thanks for the issue! I patched it up and it will be available shortly via v0.1.2.

However, please note that running your command still will result in a `MokrTimeoutError`; I _believe_ this is due to the somewhat broken implementation of the NetworkManager in Firefox and Google giving redirects. Firefox support is still experimental, unfortunately. You can run `mokr scrape --type "chrome" "https://www.google.com"` and it will work, or run `mokr scrape --type "firefox" "https://example.com"`.

All the best, and thanks for checking the project out.
